# 服务端口配置: https配置
server:
  port: 443
  ssl:
    key-store: classpath:8830354_ljy.elcfin.cn.pfx
    key-store-type: PKCS12
    key-store-password: dc8O5PfT

# 设置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1d30t40g1w2q3yfzo.mysql.rds.aliyuncs.com:3306/trade?serverTimezone=UTC
    username: root
    password: SQLroot123
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-circular-references: true
  jackson:
    generator:
      write-numbers-as-strings: true

mybatis-plus:
  mapper-locations: classpath:com/hust/trade/transaction/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hust.trade.transaction.model

spring.jackson.date-format: yyyy-MM-dd HH:mm

#这个是时区，一定要加，否则会默认为格林尼治时间，即少8小时
#spring.jackson.time-zone: GMT+8

# 分页相关配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
